### ISSUE TITLE
small islands missing after resampling

### ISSUE THREAD

**Issue by MLNoon** [ConservationInternational/trends.earth#151] opened 2018-04-17 16:19 UTC
some small islands are missing in the analysis after running the analyses. Possibly a problem with resampling. noticed in mauritius and cabo verde.

**Comment by azvoleff** [comment] 2019-12-20 18:40
@MLNoon - Can you confirm this is still an issue?

**Comment by azvoleff** [comment] 2020-03-24 13:23
@MLNoon - Can you confirm this is still an issue? And if not an issue, please close.

**Comment by azvoleff** [comment] 2020-04-01 01:24
@MLNoon - any news here?

**Comment by MLNoon** [comment] 2020-04-03 13:48
This is still a problem in Qv2, as you can see with Cabo Verde, there are two islands missing a final output, but they have both productivity and 
![Missing_data](https://user-images.githubusercontent.com/19840094/78367576-4e712600-7590-11ea-91df-7888079e0474.JPG)

**Comment by azvoleff** [comment] 2020-04-03 13:49
Best to wait and test again in QGIS3 - we aren't making any more changes to the QGIS2 version.

**Comment by MLNoon** [comment] 2020-04-03 13:51
ok. will wait until I hear from IT then and can update to the new version.

**Comment by mgroglich** [comment] 2020-04-03 15:10
I just tried in Cabo Verde using the latest version of QGIS and the plugin. The issue is not with the tool, but with the polygon dataset. Some islands area carved out from the ocean dataset, but they don't show up in the country one. @MLNoon if this issue was with the default country data, then I'd mark it as solved. If you experienced it with local datasets, then worth exploring more.
![image](https://user-images.githubusercontent.com/18239218/78376044-c1cc6500-759b-11ea-88a9-7cd0a72d6e3f.png)

**Comment by MLNoon** [comment] 2020-04-03 20:50
I get an error, so I am not sure what's next...
![image](https://user-images.githubusercontent.com/19840094/78403880-3965b880-75cb-11ea-851a-78e886012d2a.png)

**Comment by azvoleff** [comment] 2020-04-06 14:48
@MLNoon - is that with QGIS2? Or QGIS3?

**Comment by MLNoon** [comment] 2020-04-06 19:15
QGIS v 3.10.4

**Comment by azvoleff** [comment] 2020-04-06 19:23
And can you confirm this is the latest version of the plugin (from the zipfile)? It runs fine on my computer. If you do get a plugin, let me know exactly how you are running it (one step or not, etc.).

**Comment by MLNoon** [comment] 2020-04-06 19:33
0.98

**Comment by azvoleff** [comment] 2020-04-06 19:55
That isn't the latest - before you test anything else update from the zipfile. If you aren't sure what the latest development version is, you can always check here: https://github.com/ConservationInternational/trends.earth/blob/master/version.txt

Closing this for now, but reopen it if it is an issue with the latest code.

**Closed by azvoleff** 2020-04-06 19:55 UTC
Labels: bug

**Comment by MLNoon** [comment] 2020-04-06 20:06
Hm, interesting. Now it ran, but I am still missing some small islands in final output.
![image](https://user-images.githubusercontent.com/19840094/78600202-81c9e400-7820-11ea-8699-7c5b8c67d55e.png)
![image](https://user-images.githubusercontent.com/19840094/78600218-8a221f00-7820-11ea-98c8-015890f8246e.png)
