### ISSUE TITLE
Trends.Earth v2.1 error in Linux - Couldn't load plugin 'LDMP'

### ISSUE THREAD

**Issue by DimRS** [ConservationInternational/trends.earth#720] opened 2022-11-15 06:03 UTC
Hello, I am using Linux (Ubuntu 22.04) and QGIS 3.22. I upgraded to Trends.Earth v2.1 through the QGIS repository. The tool is installed, however, when I start QGIS I get the attached (inline below) related error message and the toolbox icon does not appear in QGIS, despite the fact that the tool appears to be installed in the QGIS repository. 

___________________________________

Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method

AttributeError: module 'PyQt5.QtWidgets' has no attribute 'QgsPanelWidget'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/ds/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 90, in classFactory
    from LDMP.plugin import LDMPPlugin  # noqa: autoimport
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ds/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 40, in
    from .settings import TrendsEarthOptionsFactory
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ds/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/settings.py", line 79, in
    Ui_WidgetLandCoverCustomClassEditor, _ = uic.loadUiType(
  File "/usr/lib/python3/dist-packages/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 213, in loadUiType
    ui_base = getattr(QtWidgets, baseclass)
AttributeError: module 'PyQt5.QtWidgets' has no attribute 'QgsPanelWidget'

Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
QGIS version: 3.22.4-Białowieża Białowieża, exported

Python Path:
/usr/share/qgis/python
/home/ds/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/home/ds/trends_earth_binaries_2-1_3-22
/home/ds/.local/share/QGIS/QGIS3/profiles/default/python
/home/ds/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/ds/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by azvoleff** [comment] 2022-11-15 15:27
@timlinux - is this something the Kartoza team could look into? Seems to only come up on Linux (and seems to be an issue of not being able to find the widgets that ship with QGIS)

**Comment by timlinux** [comment] 2022-11-15 22:09
Hi @azvoleff 

Yes I think @vermeulendivan  mentioned this the other day. The quick first x is to upgrade to QGIS 3.22 or later I think. @vermeulendivan please confirm.

**Comment by vermeulendivan** [comment] 2022-11-16 08:05
Hi @azvoleff @timlinux . Yes, this is the issue I came across. @Samweli also had a look at it, and replacing the QgsPanelWidget with a QWidget solves the issue in Linux. Samweli explained to me the issue is **not** with the plugin, but rather the QGIS Qt QgsPanelWidget not being available in linux. He can likely explain it better than me.

I have QGIS 3.26 installed on my linux (and on my Windows). On Linux 22.04.

There are also issues with some of the algorithms which causes a crash because in linux it can only work with 'int', but receives a 'float' for a function - this is not an issue in Windows, but is a quick fix in the code (have gotten the same issue with other plugins before). The problem is that its likely an issue with multiple algorithms, not just one. 
Would like to fix the above issues, but the network migration has been keeping me very busy.

**Comment by svallesi** [comment] 2022-11-21 21:02
Indeed, same here. I run Monterey 12.6 and QGIS 3.28.1 Firenze, trying to install the latest T.E. 2.1.2. This is the error: 

Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method 

AttributeError: module 'PyQt5.QtWidgets' has no attribute 'QgsPanelWidget' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/sergiovallesi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 90, in classFactory
    from LDMP.plugin import LDMPPlugin  # noqa: autoimport
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/sergiovallesi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 40, in 
    from .settings import TrendsEarthOptionsFactory
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/sergiovallesi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/settings.py", line 79, in 
    Ui_WidgetLandCoverCustomClassEditor, _ = uic.loadUiType(
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/PyQt5/uic/__init__.py", line 213, in loadUiType
    ui_base = getattr(QtWidgets, baseclass)
AttributeError: module 'PyQt5.QtWidgets' has no attribute 'QgsPanelWidget'


Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.28.1-Firenze Firenze, fde3b8fbb8 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/sergiovallesi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/sergiovallesi/trends_earth_binaries_2-1-2_3-28
/Users/sergiovallesi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/sergiovallesi/trends_earth_binaries_2-1-2_3-28
/Users/sergiovallesi/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/sergiovallesi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Users/sergiovallesi/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by azvoleff** [comment] 2022-11-26 20:04
See [this branch](https://github.com/ConservationInternational/trends.earth/tree/linux-fixes) for initial fixes for running on Linux/MacOS - but right now still needs work as the swap of `QWidget` for `QgsPanelWidget` creates other issues.

**Comment by Samweli** [comment] 2022-11-30 09:40
> @Samweli @vermeulendivan See [this branch](https://github.com/ConservationInternational/trends.earth/tree/linux-fixes) for initial fixes for running on Linux/MacOS - but right now still needs work as the swap of `QWidget` for `QgsPanelWidget` creates other issues.

@azvoleff I have created another PR for the `QgsPanelWidget` fix only here https://github.com/ConservationInternational/trends.earth/pull/736. We will need to also merge https://github.com/ConservationInternational/trends.earth/pull/735 which contain a fix for another plugin errror.

**Comment by azvoleff** [comment] 2022-11-30 20:52
Should now be fixed on develpo and main by 913f3416f5f3240525239d1f67fe8ba45f9eff5f.  If this still comes up can reopen this one.

**Closed by azvoleff** 2022-11-30 20:52 UTC
Labels: Bug, Kartoza
