### ISSUE TITLE
Error when downloading raw data

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#207] opened 2019-07-31 14:33 UTC
QGIS gives an error because there is no symbology assigned, but the data is downloaded correctly. There may not be much value to work on this at the moment, but could we remove the error message?

2019-07-31T10:28:58	1	Traceback (most recent call last):
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\jobs.py", line 319, in btn_download
			    download_cloud_results(job, f, self.tr)
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\jobs.py", line 408, in download_cloud_results
			    add_layer(out_file, band_number, band_info)
			  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\layers.py", line 302, in add_layer
			    tr(u'Trends.Earth does not have a style assigned for "{}" (band {} in {}). To use this layer, manually add it to your map.'.format(band_info['name'], f)))
			IndexError: tuple index out of range

**Comment by azvoleff** [comment] 2019-07-31 14:54
I’ll fix it – you are supposed to be getting a “friendly” error message, but not a Python error. Looks like I just messed up the indexing code formatting the error message, so it is throwing a Python error.

@MLNoon @mgroglich: On another note – when we talk about error messages internally we should be clear whether we are talking about an error message we are sending from the tool (a dialog box popping up with what at least I think is a helpful message 😊) or a Python error. Any time there is a Python error like the above (and traceback, etc.) that is a problem – those should never occur. Error messages we send are of course another matter.

**Comment by mgroglich** [comment] 2019-07-31 15:27
Roger that, so to differentiate them we use "Python error" vs "Friendly error"?

**Comment by azvoleff** [comment] 2019-12-20 16:31
Duplicate of #232

**Closed by azvoleff** 2019-12-20 16:31 UTC
Labels: bug, duplicate
