### ISSUE TITLE
UNCCD recommended land cover classes are not translated to Spanish 

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#674] opened 2022-07-13 19:01 UTC
![image](https://user-images.githubusercontent.com/22821787/178811097-4d868426-99bc-439d-a895-f4b603cf59a7.png)

**Comment by azvoleff** [comment] 2022-07-15 13:15
Duplicate of #677

**Closed by azvoleff** 2022-07-15 13:15 UTC
Labels: Bug, i18n
